[build]
  command = "sed -i \"s|process.env.DEPLOY_URL|'${DEPLOY_URL}'|g\" config.ts && yarn build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[template.environment]
  NEXT_PUBLIC_COMPANY_NAME = "Company name for header"
  HUB_PROJECT_UID = "Project UID of your Notehub project, e.g. app:123-456-789"
  HUB_CLIENT_ID = "Notehub API project ID"
  HUB_CLIENT_SECRET = "Notehub API project secret"
  HUB_BASE_URL = "(optional) Base URL representing the Notehub API"
  HUB_FLEET_UID = "Fleet UID for your Notehub project, e.g. fleet:987-654-321"
  DEBUG_CONFIG = "(optional) Debug config? If not '', log environment and config on server"

[context.production]
  command = "sed -i \"s|process.env.DEPLOY_URL|'${DEPLOY_URL}'|g\" config.ts && yarn build && yarn run prisma db push --accept-data-loss && yarn db:init"
  
