name: nf09-ci
on:
    workflow_dispatch:
    pull_request:
        paths:
            - "09-valve-monitor/**"

jobs:
    nf09-ci:
        uses: ./.github/workflows/platformio_ci.yml
        with:
            appid: nf09
            apppath: 09-valve-monitor
            pio_project: firmware/arduino
