name: nf34-ci
on: [push]

jobs:
  nf34-test:
    env:
        apppath: ./34-cellular-modbus-client
        project_dir:  ./34-cellular-modbus-client/firmware
        PLATFORMIO_BUILD_FLAGS: "-DNF34_NO_WAIT_FOR_SERIAL"
        PLATFORMIO_AGENT: "orangepi5b"
    runs-on: NF34
    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout: |
            .github
            ${{ env.apppath }}
      - name: Build PlatformIO Project
        # force remote so that pio compiles on the agent
        run: echo pio remote run --agent "$PLATFORMIO_AGENT" -d "$project_dir" --force-remote -p "$NF34_PORT_STLINK" -t upload
      - name: Build PlatformIO Project
        # NF34_PORT_xxx are defined in the `.env` file in the actions runner service on the self hosted runner
        run: pio remote run --agent "$PLATFORMIO_AGENT" -d "$project_dir" --force-remote -p "$NF34_PORT_STLINK" -t upload
        shell: bash
