name: nf34-ci
on:
    push:
    workflow_dispatch:

jobs:
  nf34-test:
    env:
        APP_DIR: 34-cellular-modbus-client
        PROJECT_DIR: 34-cellular-modbus-client/firmware
        PLATFORMIO_BUILD_FLAGS: "-DNF34_NO_WAIT_FOR_SERIAL"
    runs-on: NF34
    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout: |
            .github
            ${{ env.APP_DIR }}
      - name: Build PlatformIO Project
        # NF34_PORT_xxx are defined in the `.env` file in the actions runner service on the self hosted runner
        run: |
            pwd
            ls
            pio remote -a "$PLATFORMIO_AGENT" run -d "$project_dir" --force-remote --upload-port "$NF34_PORT_STLINK" -t upload
      - name: Setup Python version
        uses: actions/setup-python@v4
        with:
            python-version: '3.11'
      - name: Create and start virtual environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run NF34 test script
        # configuration provided by the environment variables on the runner
        run: python test.py
