name: nf34-ci
on: [push]

jobs:
  nf34-test:
    env:
        apppath: ./34-cellular-modbus-client
        project_dir:  ./34-cellular-modbus-client/firmware
        PLATFORMIO_BUILD_FLAGS: "-DNF34_NO_WAIT_FOR_SERIAL"
        PLATFORMIO_AGENT: "orangepi5b"
    runs-on: NF34
    steps:
      - uses: actions/checkout@v3
      - name: Build PlatformIO Project
        # force remote so that pio compiles on the agent
        run: echo pio remote run -a "$PLATFORMIO_AGENT" -d "$project_dir" --force-remote -p "$NF34_PORT_STLINK" -t upload
      - name: Build PlatformIO Project
        run: pio remote run -a "$PLATFORMIO_AGENT" -d "$project_dir" --force-remote -p "$NF34_PORT_STLINK" -t upload
        shell: bash
