name: nf36-ci
on:
    workflow_dispatch:
    pull_request:
        paths:
            - "36-vending-machine-monitor/**"

jobs:
    nf35-ci:
        uses: ./.github/workflows/platformio_ci.yml
        with:
            appid: nf36
            apppath: 36-vending-machine-monitor
            pio_project: firmware
